
version: 2

models:
  - name: stg_users
    description: "users"
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_addresses
    description: "users address"
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_events
    description: "users events"
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: "users orders"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_order_items
    description: "users orders items"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_products
    description: "users orders items"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_promos
    description: "order promotion"
    columns:
      - name: promos_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  

 